# Generated by Django 4.1.5 on 2023-01-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_slug_post_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='null', max_length=200),
        ),
    ]
